### PR TITLE
Wndows Universal a suport - need to do the wiring from config.xml

### PR DESCRIPTION
**Pull request by Pavel-Durov**
I've followed the logic of your wp8 platforms implementation. I've added the UWP ("windwos") platform: In order to show WinJs flyout I needed to inject an object to the document's body and afterward I could manipulate it accordingly to sent parameters.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
That's very cool, thanks for taking the time implementing this!

Don't you need to add some bits to `plugin.xml` to make this work though?

**Comment by Pavel-Durov** [comment]
Yes you are right, I've just encounter some issues with plugin.xml configurations - I've posted it on stackoverflow : http://stackoverflow.com/questions/33472478/cordova-plugin-config-xml-uwp-windows-platformid.

**Comment by Pavel-Durov** [comment]
I've made a push with the config.xml changes...

**Comment by EddyVerbruggen** [comment]
Supernice, @Pavel-Durov!

I've made you a collaborator on the repo, so if you even need to change anything (especially for windows suppor) then feel free to go right ahead!

**Comment by Pavel-Durov** [comment]
Thanks! 
I think I've just got a clue on how to solve the config.xml issue :).

**Pull request merged**
